; 問い合わせメールアカウント情報
[INQUIRY]
HOST = "smtp.example.com"
USERNAME = "info@example.com"
PASSWORD = "xxxxxx"
PORT = 587
SEND_ADDRESS = "info@example.com"
RECV_ADDRESS = "info@example.com"
MAIL_SUBJECT = "【送信完了】お問い合わせを受け付けました｜株式会社タイム"
MAIL_CONFIRM_SUBJECT = "【送信完了】お問い合わせを受け付けました｜株式会社タイム"

; 問い合わせメールアカウント情報(デバッグ用)
; デバッグモードが有効な場合は、INQUIRYではなくこの設定が適用される
[INQUIRY_DEBUG]
HOST = "sv16458.xserver.jp"
USERNAME = "test.gunji@vgunji0527.xsrv.jp"
PASSWORD = "rikuo-0527"
PORT = 587
SEND_ADDRESS = "test.gunji@vgunji0527.xsrv.jp"
RECV_ADDRESS = "ident.karby@gmail.com"
MAIL_SUBJECT = "[テスト]【送信完了】お問い合わせを受け付けました｜株式会社タイム"
MAIL_CONFIRM_SUBJECT = "[テスト]【送信完了】お問い合わせを受け付けました｜株式会社タイム"
