[System]
; ファイルの最大サイズ(10MB)(0以下の場合はチェックしない)
; MAX_FILE_SIZE = 1024 * 1024 * 10
MAX_FILE_SIZE = -1
; デバッグモード(trueの場合はデバッグログを出力する)
IS_DEBUG = false
; デバッグログをページに出力するかどうか(IS_DEBUGがtrueかつtrueの場合はデバッグログをページに出力する)
IS_WRITE_DEBUG_LOG_ON_PAGE = false
; キャッシュを無効にするかどうか(IS_DEBUGがtrueかつtrueの場合はキャッシュを無効にする)
IS_DISABLE_CACHE = false
; デバッグログをファイルに出力するかどうか(IS_DEBUGがtrueかつtrueの場合はデバッグログをファイルに出力する)
IS_WRITE_DEBUG_LOG_ON_FILE = false